kind: pipeline
type: kubernetes
name: default

steps:
- name: greeting
  image: alpine
  commands:
  - echo hello
  - echo world

- name: greeting2
  image: alpine
  commands:
  - echo hello
  - echo world

trigger:
  branch:
  - master
  event:
  - push